plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ativadorunitv.revendedor'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ativadorunitv.revendedor'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
